[package]
name = "rs_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
libc = "0.2.0"

[build-dependencies]
cbindgen = "0.26"
