# Конфигурация для spring + (в перспективе) postgresql

version: '3'
services:
  app-wiremock:
    image: wiremock/wiremock:3.4.2
    ports:
      - "8080:8080"
    volumes:
#      - ./__files:/home/wiremock/__files
      - ./volumes/wm-marketplace/mappings:/home/wiremock/mappings
#    entrypoint: ["/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose"]
