# Минимальная версия инфраструктуры на базе
# OpenSearch - хранилище логов и метрик
# OpenSearch Dashboards - отрисовка логов
# Fluent Bit - служба сбора логов
# Envoy - прокси
# Keycloak - сервер идентификации

# Адреса:
# Приложение доступно по http://localhost:8090 (envoy прокси)
# Панели мониторинга http://localhost:5601 (opensearch dashboards, kibana)
# Управление пользователями http://localhost:8081 (keycloak)

version: '3'
services:

  app:
    image: nginx:latest
#    ports:
#      - "8080:80"
    depends_on:
      - fluent-bit
      - envoy
    volumes:
      - ./volumes/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./volumes/nginx/nginx.conf:/etc/nginx/nginx.conf
    logging:
      # используемый драйвер логгирования
      driver: "fluentd"
      options:
        # куда посылать лог-сообщения, необходимо чтобы адрес
        # совпадал с настройками плагина forward
        fluentd-address: localhost:24224
        # теги используются для маршрутизации лог-сообщений, тема
        # маршрутизации будет рассмотрена ниже
        tag: app.logs

  fluent-bit:
    container_name: fluent-bit
    image: fluent/fluent-bit
    ports:
      # необходимо открыть порты, которые используются плагином forward
      - "24224:24224"
      - "24224:24224/udp"
      - "2020:2020"
    environment:
      - opensearch_host=opensearch
      - opensearch_user=admin
      - opensearch_pass=admin
    volumes:
      - ./volumes/fluent-bit-etc/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./volumes/fluent-bit-etc/parsers.conf:/fluent-bit/etc/parsers.conf

  opensearch:
    container_name: opensearch
    image: opensearchproject/opensearch:latest
    environment:
      - discovery.type=single-node
      - http.port=9200
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - '9200:9200'
      - '9600:9600'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data

  dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
    depends_on:
      - opensearch

  envoy:
    image: envoyproxy/envoy:v1.29.0  # Use the official Envoy proxy image
    volumes:
      - ./volumes/envoy/envoy.yaml:/etc/envoy/envoy.yaml  # Mount your Envoy configuration file
    #      - ./envoy/certs:/etc/envoy/certs  # Mount your TLS certificates
    ports:
      - "15001:15001"
      - "8090:8090"

  keycloak:
    #    image: jboss/keycloak:latest
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8081:8080"
      - "8082:9990"
    volumes:
      #      - ./keycloak:/tmp
      - ./volumes/keycloak/import:/opt/keycloak/data/import
    #      - ./keycloak/standalone.xml:/opt/jboss/keycloak/standalone/configuration/standalone.xml
    #      - ./keycloak/certs/keycloak.jks:/etc/x509/https/keystore  # Mount your Keycloak keystore
    environment:
      KEYCLOAK_USER: otus
      KEYCLOAK_PASSWORD: otus
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: "/tmp/realm-export.json"
    command:
      - start-dev
      #      - --features admin-fine-grained-authz
      - --hostname-port=8081
      - --import-realm

volumes:
  opensearch-data:
