version: "3.3"
services:
  arcadedb:
    image: "arcadedata/arcadedb:24.4.1"
    ports:
      - "2480:2480"
      - "2424:2424"
      - "8182:8182"
#    volumes:
#      - ./volumes/arcadedb:/home/arcadedb/databases
       # Здесь можно добавить доступные через gremlin графы и псевдонимы
#      - ./volumes/arcadedb:/home/arcadedb/config/gremlin-server.groovy
    environment:
      JAVA_OPTS: > 
        -Darcadedb.server.rootPassword=root_root
        -Darcadedb.server.plugins=GremlinServer:com.arcadedb.server.gremlin.GremlinServerPlugin
